/*
 * Copyright (c) 2016-2022 Vera Visions LLC.
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
 * IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

/* inspired by https://developer.valvesoftware.com/wiki/Inputs_and_Outputs 
   a lot of the action happens in ncIO.
*/

/** This entity class represents a child-output, generated by ncIO's modern trigger system. */
class ncOutput:ncEntity
{
private:
	entity m_eActivator;
	string m_strTarget;
	string m_strInput;
	string m_strData;
	float m_flDelay;
	int m_iCount;
	int m_iOldCount;

public:
	void ncOutput(void);

	/** Call to trigger the ncOutput's target. */
	virtual void TriggerOutput(void);

	virtual void ScheduleOutput(entity);

	/** Internal use only. */
	virtual void Init(void);
	/** Internal use only. */
	virtual void Respawn(void);
};
