#!/bin/sh
set -e
SCRPATH="$( cd "$( dirname $(readlink -nf $0) )" && pwd )"

# We want to keep our library separate
if [ -d "$HOME/Library/Games" ]
then
	ADDITIONAL_ARGS="-usehome -homedir ${HOME}/Library/Games/Nuclide"
fi


cd "$SRCPATH/bin"

if [ -f "$SRCPATH/bin/fteqw-sv" ]; then
	if [ -z "$NUCLIDE_GDB" ]; then
		./fteqw-sv ${ADDITIONAL_ARGS} -basedir ../ $*
	else
		gdb --args ./fteqw ${ADDITIONAL_ARGS} -basedir ../ $*
	fi
else
	printf "Engine is not present, please run build_engine.sh\n"
f