#!/bin/sh
set -e
SCRPATH="$( cd "$( dirname $(readlink -nf $0) )" && pwd )"
PATH="$SCRPATH"/bin:"$PATH"

if [ -f "$SCRPATH"/bin/fteqw ]; then
	fteqw -manifest valve.fmf $*
else
	printf "Engine is not present, please run build_engine.sh\n"
fi
