#!/bin/sh
set -e
SRCPATH="$( cd "$( dirname $(readlink -nf $0) )" && pwd )"

cd "$SRCPATH/bin"

if [ -f "$SRCPATH"/bin/fteqw ]; then
	if [[ -z "${NUCLIDE_GDB}" ]]; then
		./fteqw -basedir ../ $*
	else
		gdb --args ./fteqw -basedir ../ $*
	fi
else
	printf "Engine is not present, please run build_engine.sh\n"
fi
