#!/bin/sh
SCRPATH="$( cd "$( dirname $(readlink -nf $0) )" && pwd )"
PATH="$SCRPATH"/bin:"$PATH"

if [ ! -f "$SCRPATH"/bin/vmap ]; then
	printf "Map compiler is not present, please run build_editor.sh\n"
	exit
fi

"$SCRPATH"/bin/vmap -v -custinfoparms -fs_basepath "$SCRPATH" -fs_game platform -threads 4 -samplesize 8 $*

if [ ! -f "$*.prt" ]; then
	exit
fi

"$SCRPATH"/bin/vmap -vis -v -fs_basepath "$SCRPATH" -fs_game platform $*
"$SCRPATH"/bin/vmap -light -custinfoparms -fs_basepath "$SCRPATH" -v -fs_game platform -bounce 8 -fastbounce -samplesize 8 -threads 4 -shade -shadeangle 60 -patchshadows $*



