
/* File generated by FTEQCC, relevent for engine modding only, the generated crc must be the same as your engine expects. */

typedef struct globalvars_s
{
	int ofs_null;
	int ofs_return[3];
	int ofs_parm0[3];
	int ofs_parm1[3];
	int ofs_parm2[3];
	int ofs_parm3[3];
	int ofs_parm4[3];
	int ofs_parm5[3];
	int ofs_parm6[3];
	int ofs_parm7[3];
	int	self;
	int	other;
	int	world;
	float	time;
	float	cltime;
	float	frametime;
	float	player_localentnum;
	float	player_localnum;
	float	maxclients;
	float	clientcommandframe;
	float	servercommandframe;
	string_t	mapname;
	float	intermission;
	vec3_t	v_forward;
	vec3_t	v_up;
	vec3_t	v_right;
	vec3_t	view_angles;
	float	trace_allsolid;
	float	trace_startsolid;
	float	trace_fraction;
	vec3_t	trace_endpos;
	vec3_t	trace_plane_normal;
	float	trace_plane_dist;
	int	trace_ent;
	float	trace_inopen;
	float	trace_inwater;
	float	input_timelength;
	vec3_t	input_angles;
	vec3_t	input_movevalues;
	float	input_buttons;
	float	input_impulse;
} globalvars_t;

typedef struct entvars_s
{
	float	modelindex;
	vec3_t	absmin;
	vec3_t	absmax;
	float	entnum;
	float	drawmask;
	func_t	predraw;
	func_t	ncDecal::__mpredraw;
	func_t	ncEntity::__mpredraw;
	func_t	func_dustcloud_cloud::__mpredraw;
	func_t	func_smokevolume_cloud::__mpredraw;
	func_t	env_steam_particle::__mpredraw;
	float	movetype;
	float	solid;
	vec3_t	origin;
	vec3_t	oldorigin;
	vec3_t	velocity;
	vec3_t	angles;
	vec3_t	avelocity;
	float	pmove_flags;
	string_t	classname;
	float	renderflags;
	string_t	model;
	float	frame;
	float	frame1time;
	float	frame2;
	float	frame2time;
	float	lerpfrac;
	float	skin;
	float	effects;
	vec3_t	mins;
	vec3_t	maxs;
	vec3_t	size;
	func_t	touch;
	func_t	think;
	func_t	env_sprite::__mthink;
	func_t	blocked;
	float	nextthink;
	int	chain;
	int	enemy;
	float	flags;
	float	colormap;
	int	owner;
} entvars_t;

#define PROGHEADER_CRC 42444
