class
info_target:ncPointTrigger
{
	void info_target(void);
};

void
info_target::info_target(void)
{

}

class
target_position:ncPointTrigger
{
	void target_position(void);
};

void
target_position::target_position(void)
{

}

class
misc_teleporter_dest:ncPointTrigger
{
	void misc_teleporter_dest(void);
};

void
misc_teleporter_dest::misc_teleporter_dest(void)
{

}



class
target_location:ncPointTrigger
{
	void target_location(void);
};

void
target_location::target_location(void)
{

}
