QCC=fteqcc

all:
	mkdir -p ../../progs/
	$(QCC) $(CFLAGS) deathmatch.src
	$(QCC) $(CFLAGS) singleplayer.src
	$(QCC) $(CFLAGS) invasion.src
	$(QCC) $(CFLAGS) domination.src
	$(QCC) $(CFLAGS) lastmanstanding.src
	$(QCC) $(CFLAGS) teamdm.src
