/*
 * Copyright (c) 2016-2019 Marco Hladik <marco@icculus.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
 * IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/* Weapon Indices for the weapon table */
enum
{
	WEAPON_NONE,
	WEAPON_CROWBAR,
	WEAPON_PIPEWRENCH,
	WEAPON_KNIFE,
	WEAPON_GRAPPLE,
	WEAPON_GLOCK,
	WEAPON_PYTHON,
	WEAPON_EAGLE,
	WEAPON_MP5,
	WEAPON_SHOTGUN,
	WEAPON_CROSSBOW,
	WEAPON_RPG,
	WEAPON_GAUSS,
	WEAPON_EGON,
	WEAPON_HORNETGUN,
	WEAPON_HANDGRENADE,
	WEAPON_SATCHEL,
	WEAPON_TRIPMINE,
	WEAPON_SNARK,
	WEAPON_PENGUIN,
	WEAPON_M249,
	WEAPON_DISPLACER,
	WEAPON_SNIPERRIFLE,
	WEAPON_SPORELAUNCHER,
	WEAPON_SHOCKRIFLE
};

/* What the weapons do support and stuff */
enum
{
	AMMO_9MM,
	AMMO_357,
	AMMO_BUCKSHOT,
	AMMO_M203_GRENADE,
	AMMO_BOLT,
	AMMO_ROCKET,
	AMMO_URANIUM,
	AMMO_HANDGRENADE,
	AMMO_SATCHEL,
	AMMO_TRIPMINE,
	AMMO_SNARK,
	AMMO_556,
	AMMO_762,
	AMMO_SPORE
};
