CC=fteqcc

qc-progs:
	$(CC) menu-fn/progs.src
	mkdir -p ../valve/data.pk3dir
	$(CC) client/valve/progs.src
	$(CC) server/valve/progs.src
	mkdir -p ../scihunt/data.pk3dir
	$(CC) client/scihunt/progs.src
	$(CC) server/scihunt/progs.src
	mkdir -p ../cstrike/data.pk3dir
	$(CC) client/cstrike/progs.src
	$(CC) server/cstrike/progs.src
	mkdir -p ../rewolf/data.pk3dir
	$(CC) client/rewolf/progs.src
	$(CC) server/rewolf/progs.src
	mkdir -p ../tfc/data.pk3dir
	$(CC) client/tfc/progs.src
	$(CC) server/tfc/progs.src
