CC=fteqcc

qc-progs:
	$(CC) menu-fn/progs.src
	mkdir -p ../valve/data.pk3dir
	$(CC) client/valve.src
	$(CC) server/valve.src
	mkdir -p ../scihunt/data.pk3dir
	$(CC) client/scihunt.src
	$(CC) server/scihunt.src
	mkdir -p ../cstrike/data.pk3dir
	$(CC) client/cstrike.src
	$(CC) server/cstrike.src
	mkdir -p ../rewolf/data.pk3dir
	$(CC) client/rewolf.src
	$(CC) server/rewolf.src
