CC=fteqcc

qc-progs:
	$(CC) menu-fn/progs.src
	$(CC) client/valve.src
	$(CC) server/valve.src
	$(CC) client/scihunt.src
	$(CC) server/scihunt.src
	$(CC) client/cstrike.src
	$(CC) server/cstrike.src
	$(CC) client/rewolf.src
	$(CC) server/rewolf.src
