/*
 * Copyright (c) 2016-2019 Marco Hladik <marco@icculus.org>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF MIND, USE, DATA OR PROFITS, WHETHER
 * IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

/* weapon Indices for the weapon table */
enum
{
	WEAPON_NONE,
	WEAPON_CROWBAR,
	WEAPON_MEDKIT,
	WEAPON_KNIFE,
	WEAPON_WRENCH,
	WEAPON_UMBRELLA,
	WEAPON_SBS,
	WEAPON_SNIPER,
	WEAPON_TRANQUIL,
	WEAPON_RAILGUN,
	WEAPON_AUTORIFLE,
	WEAPON_DBS,
	WEAPON_NAILGUN,
	WEAPON_GLAUNCHER,
	WEAPON_SUPERNAIL,
	WEAPON_FLAMER,
	WEAPON_RPG,
	WEAPON_PIPEBOMB,
	WEAPON_ASSCAN,
	WEAPON_INCENDIARY,
	WEAPON_GRAPPLE
};

/* What the weapons do support and stuff */
enum
{
	AMMO_SHELLS,
	AMMO_NAILS,
	AMMO_ROCKETS,
	AMMO_CELLS
};
